const searchMarsRoversCapturedPhotos = 'searchMarsRoversCapturedPhotos',
    nasaKeyApi = 'NpRGSKyi5LzJO3uckC1UabCrScL8MJjWVgQehtBz',
    viewPageAniamtionDuration = 1, // seconds
    screenSaverImageSize = 128, // pixels
    numberOfImagesToStartGrid = 10,
    screenSaverInitialAnimationDurationTime = 0.01, // seconds
    screenSaverInitialAnimationOffsetTime = 0, // seconds
    screenSaverAnimationDurationTime = 0.5, // seconds
    screenSaverAnimationOffsetTime = 1; // seconds