const searchMarsRoversCapturedPhotos = 'search-mars-rovers-captured-photos',
    nasaKeyApi = 'NpRGSKyi5LzJO3uckC1UabCrScL8MJjWVgQehtBz',
    viewPageAniamtionDuration = 1, // seconds
    screenSaverImageSize = 128, // pixels
    numberOfImagesToStartGrid = 10,
    screenSaverInitialAnimationDurationTime = 0.2, // seconds
    screenSaverInitialAnimationOffsetTime = 0.2, // seconds
    screenSaverAnimationDurationTime = 1, // seconds
    screenSaverAnimationOffsetTime = 1; // seconds