const searchMarsRoversCapturedPhotos = 'search-mars-rovers-captured-photos',
    nasaKeyApi = '7YnczC4xpaqneFnfnNj763DZwejqt0mae3ofAWie',
    togglePageAniamtionDuration = 1, // seconds
    screenSaverImageSize = 128, // pixels
    numberOfImagesToStartGrid = 10,
    screenSaverInitialAnimationDurationTime = 0.2, // seconds
    screenSaverInitialAnimationOffsetTime = 0.2, // seconds
    screenSaverAnimationDurationTime = 1, // seconds
    screenSaverAnimationOffsetTime = 1; // seconds